{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "email-converter.fullname" . }}-api
  namespace: {{ include "email-converter.namespace" . }}
  labels:
    {{- include "email-converter.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "email-converter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
