from src.modules.conversion.strategies.base import (
    ConversionStrategy,
    ConversionContext,
    ConversionResult,
)


class MarkdownConversionStrategy(ConversionStrategy):
    def get_format(self) -> str:
        return "markdown"

    def get_content_type(self) -> str:
        return "text/markdown"

    def get_file_extension(self) -> str:
        return ".md"

    def validate_context(self, context: ConversionContext) -> list[str]:
        return []

    async def convert(self, context: ConversionContext) -> ConversionResult:
        errors = self.validate_context(context)
        if errors:
            return ConversionResult(success=False, errors=errors)

        try:
            md_content = self._generate_markdown(context)
            filename = self.get_default_filename(context)

            return ConversionResult(
                success=True,
                content=md_content,
                filename=filename,
                content_type=self.get_content_type(),
                file_size=len(md_content.encode("utf-8")),
                metadata={
                    "format": "markdown",
                    "renderable": True,
                },
            )

        except Exception as e:
            return ConversionResult(
                success=False,
                errors=[f"Markdown conversion failed: {str(e)}"],
            )

    def _generate_markdown(self, context: ConversionContext) -> str:
        lines = []

        lines.append(f"# {context.subject or 'No Subject'}")
        lines.append("")

        lines.append("## Email Information")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| **From** | {context.from_address or 'Unknown'} |")

        if context.to_addresses:
            lines.append(f"| **To** | {', '.join(context.to_addresses)} |")

        if context.cc_addresses:
            lines.append(f"| **Cc** | {', '.join(context.cc_addresses)} |")

        lines.append(f"| **Date** | {self._format_date(context.date)} |")
        lines.append("")

        lines.append("## Content")
        lines.append("")

        if context.text_body:
            lines.append("```")
            lines.append(context.text_body)
            lines.append("```")
        elif context.html_body:
            lines.append("<details>")
            lines.append("<summary>HTML Content</summary>")
            lines.append("")
            lines.append("```html")
            lines.append(context.html_body)
            lines.append("```")
            lines.append("")
            lines.append("</details>")
        else:
            lines.append("*No content*")

        lines.append("")

        if context.attachments:
            lines.append("## Attachments")
            lines.append("")
            lines.append("| # | Filename | Size | Type |")
            lines.append("|---|----------|------|------|")

            for i, att in enumerate(context.attachments, 1):
                filename = att.get("filename", "attachment")
                size = att.get("file_size", 0)
                content_type = att.get("content_type", "unknown")
                lines.append(f"| {i} | {filename} | {self._format_size(size)} | {content_type} |")

            lines.append("")

        lines.append("---")
        lines.append("*Generated by Email Converter SaaS*")

        return "\n".join(lines)

    def _format_size(self, size: int) -> str:
        for unit in ["B", "KB", "MB", "GB"]:
            if size < 1024:
                return f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} TB"
