from src.modules.conversion.strategies.base import (
    ConversionStrategy,
    ConversionContext,
    ConversionResult,
)


class TxtConversionStrategy(ConversionStrategy):
    def get_format(self) -> str:
        return "txt"

    def get_content_type(self) -> str:
        return "text/plain"

    def get_file_extension(self) -> str:
        return ".txt"

    def validate_context(self, context: ConversionContext) -> list[str]:
        return []

    async def convert(self, context: ConversionContext) -> ConversionResult:
        errors = self.validate_context(context)
        if errors:
            return ConversionResult(success=False, errors=errors)

        try:
            text_content = self._generate_text(context)
            filename = self.get_default_filename(context)

            return ConversionResult(
                success=True,
                content=text_content,
                filename=filename,
                content_type=self.get_content_type(),
                file_size=len(text_content.encode("utf-8")),
                metadata={
                    "format": "txt",
                    "plain_text": True,
                },
            )

        except Exception as e:
            return ConversionResult(
                success=False,
                errors=[f"TXT conversion failed: {str(e)}"],
            )

    def _generate_text(self, context: ConversionContext) -> str:
        lines = []

        lines.append("=" * 60)
        lines.append("EMAIL HEADER")
        lines.append("=" * 60)
        lines.append("")

        lines.append(f"Subject: {context.subject or 'No Subject'}")
        lines.append(f"From: {context.from_address or 'Unknown'}")

        if context.to_addresses:
            lines.append(f"To: {', '.join(context.to_addresses)}")

        if context.cc_addresses:
            lines.append(f"Cc: {', '.join(context.cc_addresses)}")

        lines.append(f"Date: {self._format_date(context.date)}")

        if context.headers:
            for key, value in context.headers.items():
                if key.lower() not in ("from", "to", "cc", "subject", "date"):
                    if isinstance(value, list):
                        value = ", ".join(value)
                    lines.append(f"{key}: {value}")

        lines.append("")
        lines.append("=" * 60)
        lines.append("EMAIL BODY")
        lines.append("=" * 60)
        lines.append("")

        if context.text_body:
            wrapped = self._wrap_text(context.text_body, 72)
            lines.append(wrapped)
        elif context.html_body:
            plain = self._html_to_text(context.html_body)
            wrapped = self._wrap_text(plain, 72)
            lines.append(wrapped)
        else:
            lines.append("[No content]")

        if context.attachments:
            lines.append("")
            lines.append("=" * 60)
            lines.append("ATTACHMENTS")
            lines.append("=" * 60)
            lines.append("")

            for i, att in enumerate(context.attachments, 1):
                filename = att.get("filename", "attachment")
                size = att.get("file_size", 0)
                content_type = att.get("content_type", "unknown")
                lines.append(f"{i}. {filename}")
                lines.append(f"   Size: {self._format_size(size)}")
                lines.append(f"   Type: {content_type}")
                lines.append("")

        lines.append("")
        lines.append("=" * 60)
        lines.append("Generated by Email Converter SaaS")
        lines.append("=" * 60)

        return "\n".join(lines)

    def _wrap_text(self, text: str, width: int = 72) -> str:
        words = text.split()
        lines = []
        current_line = []
        current_length = 0

        for word in words:
            if current_length + len(word) + 1 <= width:
                current_line.append(word)
                current_length += len(word) + 1
            else:
                if current_line:
                    lines.append(" ".join(current_line))
                current_line = [word]
                current_length = len(word)

        if current_line:
            lines.append(" ".join(current_line))

        return "\n".join(lines)

    def _html_to_text(self, html: str) -> str:
        import re
        text = re.sub(r"<br\s*/?>", "\n", html, flags=re.IGNORECASE)
        text = re.sub(r"<p[^>]*>", "\n", text, flags=re.IGNORECASE)
        text = re.sub(r"</p>", "\n", text, flags=re.IGNORECASE)
        text = re.sub(r"<[^>]+>", "", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        return text.strip()

    def _format_size(self, size: int) -> str:
        for unit in ["B", "KB", "MB", "GB"]:
            if size < 1024:
                return f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} TB"
